services:
  - type: web
    name: iamcalling
    env: node
    rootDir: iamcalling
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 1000
      - key: CORS_ORIGIN
        value: "*"
